"""
    We observe the types of events performed by the bots. The query in Figure 3.1 shows the query that
    returns the number of events of each type generated by these six accounts.

This script uses that query and shows its results.
"""

import duckdb

events = "read_json_auto('../../data/events/*.json', filename = true, union_by_name = true)"
bots = ['marge-bot', 'translations', 'gnome-build-meta-bot', 'support-bot', 'project_16754_bot_2b6da7b077af381b7f45e5a10781e7db', 'project_25833_bot_a55d157583ed16b001006899b37d7846']

QUERY = f"""
SELECT author.username, action_name, target_type, COUNT(*)
FROM {events}
WHERE author.username IN {bots}
GROUP BY 1, 2, 3
ORDER BY SUM(COUNT(*)) OVER (PARTITION BY author.username) DESC, 4 DESC, 2, 3
"""

duckdb.sql(QUERY).show()
